test

diff --git a/shared-functions b/shared-functions
--- a/shared-functions
+++ b/shared-functions
@@ -415,6 +415,30 @@ setup_password_from_credhub() {
   set -x
 }
 
+upload_stemcells() {
+  local arguments=''
+  for op in ${OPS_FILES}
+  do
+    arguments="${arguments} -o ops-files/${op}"
+  done
+
+  bosh interpolate ${arguments} cf-deployment/${MANIFEST_FILE} > /tmp/cf.yml
+
+  local stemcells_json=$(ruby -rjson -ryaml -e "puts YAML.load_file('/tmp/cf.yml').to_json" | jq .stemcells)
+  local size=$(echo ${stemcells_json} | jq 'length')
+  if [ ${size} -eq 0 ]; then
+    echo "Error: Did not find any stemcells to upload."
+    exit 1
+  fi
+
+  for i in `seq 0 $((size - 1))`
+  do
+    local os=$(echo ${stemcells_json} | jq -r .[$i].os)
+    local version=$(echo ${stemcells_json} | jq -r .[$i].version)
+    upload_stemcell ${os} ${version}
+  done
+}
+
 upload_stemcell() {
   # Read potentially variable stemcell parameters
   local os=$1
