tesT

diff --git a/shared-functions b/shared-functions
--- a/shared-functions
+++ b/shared-functions
@@ -449,10 +449,8 @@ upload_stemcells() {
 
   bosh interpolate ${arguments} cf-deployment/${MANIFEST_FILE} > /tmp/cf.yml
 
-  local stemcells_json
-  stemcells_json=$(ruby -rjson -ryaml -e "puts YAML.load_file('/tmp/cf.yml').to_json" | jq .stemcells)
-  local size
-  size=$(echo ${stemcells_json} | jq 'length')
+  local stemcells_json=$(ruby -rjson -ryaml -e "puts YAML.load_file('/tmp/cf.yml').to_json" | jq .stemcells)
+  local size=$(echo ${stemcells_json} | jq 'length')
   if [ ${size} -eq 0 ]; then
     echo "Error: Did not find any stemcells to upload."
     exit 1
@@ -460,45 +458,41 @@ upload_stemcells() {
 
   for i in `seq 0 $((size - 1))`
   do
-    local os
-    os=$(echo ${stemcells_json} | jq -r .[$i].os)
-    local version
-    version=$(echo ${stemcells_json} | jq -r .[$i].version)
+    local os=$(echo ${stemcells_json} | jq -r .[$i].os)
+    local version=$(echo ${stemcells_json} | jq -r .[$i].version)
     upload_stemcell ${os} ${version}
   done
 }
 
 upload_stemcell() {
-  local os=$1
-  local version=$2
-  local stemcells_url="https://bosh.io/d/stemcells"
+  # Read potentially variable stemcell paramaters out of cf-deployment with bosh
+  local os
+  os=$1
+  local version
+  version=$2
 
-  # Skip Windows stemcells entirely
-  if [[ "$os" == windows* ]]; then
-    echo "INFO: Skipping Windows stemcell for OS '$os'"
-    return 0
-  fi
+  # Hardcode a couple of stable stemcell paramaters
+  local stemcells_url
+  stemcells_url="https://bosh.io/d/stemcells"
 
-  # Check if BOSH already has this stemcell
+  # Ask bosh if it already has our OS / version stemcell combination
+  # As of this writing, the new bosh cli doesn't have --skip-if-exists
   set +e
   local existing_stemcell
-  existing_stemcell=$(bosh stemcells | grep "${os}" | awk '{print $2}' | tr -d "*" | grep "^${version}$")
+  existing_stemcell=$(bosh stemcells | grep "${os}" | awk '{print $2}' | tr -d "\*" | grep ^"${version}"$ )
   set -e
 
   local stemcell_name
-  local infrastructure
 
-  if [ "${BOSH_LITE}" == "true" ]; then
+  local infrastructure
+  if [ "${BOSH_LITE}" == "true"  ]; then
     infrastructure="bosh-lite"
     stemcell_name="bosh-warden-boshlite"
-    echo "DEBUG: Using bosh-lite/Warden stemcell"
-  elif [[ "$SHEPHERD_POOL" == "cfd" ]]; then
-    infrastructure="bosh-lite"
-    stemcell_name="bosh-warden-boshlite"
-    echo "DEBUG: CFD pool uses Warden; using bosh-warden-boshlite stemcell"
+  elif [ -d toolsmiths-env ]; then
+    infrastructure="gcp"
+    stemcell_name="bosh-google-kvm"
   else
     infrastructure="$(jq -r .iaas bbl-state/${BBL_STATE_DIR}/bbl-state.json)"
-    echo "DEBUG: IAAS from bbl-state=${infrastructure}"
 
     if [ "$infrastructure" = "aws" ]; then
       stemcell_name="bosh-aws-xen-hvm"
@@ -513,35 +507,34 @@ upload_stemcell() {
     fi
   fi
 
-  # Finalize stemcell name
   stemcell_name="${stemcell_name}-${os}-go_agent"
-
-  # Build stemcell URL
-  local full_stemcell_url
   if [ "$version" = "latest" ]; then
     full_stemcell_url="${stemcells_url}/${stemcell_name}"
   else
     full_stemcell_url="${stemcells_url}/${stemcell_name}?v=${version}"
   fi
 
-  # Skip if stemcell already exists
+  # If bosh already has our stemcell, exit 0
   if [ "${existing_stemcell}" ]; then
     echo "Task bosh-upload-stemcell-from-cf-deployment:"
-    echo "Stemcell '${stemcell_name}/${version}' already exists. Skipping..."
-    return 0
+    echo "Stemcell '${stemcell_name}/${version}' already exists.  Skipping..."
+    return
   fi
 
-  # Check if stemcell exists on bosh.io
+  # If bosh.io doesn't have our stemcell, exit 2
   set +e
+  local stemcell_exists
   wget -S --spider "${full_stemcell_url}" > /dev/null 2>&1
-  local stemcell_exists=$?
-  set -e
+  stemcell_exists=$?
   if [ ${stemcell_exists} -ne 0 ]; then
-    echo "INFO: Stemcell '${os}/${version}' not found on bosh.io. Skipping upload."
-    return 0
+    echo "Error: Could not find a '$os' stemcell for IaaS '$infrastructure' on bosh.io. Please double-check that the IaaS/OS combination is supported."
+    exit 2 #POSIX 'No such file or directory'
   fi
+  set -e
 
-  # Upload stemcell
-  echo "Uploading stemcell '${stemcell_name}/${version}'..."
-  bosh -n upload-stemcell "${full_stemcell_url}"
+  # ... otherwise, begin the upload process
+  bosh \
+    -n \
+    upload-stemcell \
+    "${full_stemcell_url}"
 }
