tesT

diff --git a/shared-functions b/shared-functions
--- a/shared-functions
+++ b/shared-functions
@@ -465,47 +465,58 @@ upload_stemcells() {
 }
 
 upload_stemcell() {
-  # Read potentially variable stemcell paramaters out of cf-deployment with bosh
-  local os
-  os=$1
-  local version
-  version=$2
+  local os=$1
+  local version=$2
 
-  # Hardcode a couple of stable stemcell paramaters
-  local stemcells_url
-  stemcells_url="https://bosh.io/d/stemcells"
+  local stemcells_url="https://bosh.io/d/stemcells"
 
   # Ask bosh if it already has our OS / version stemcell combination
-  # As of this writing, the new bosh cli doesn't have --skip-if-exists
   set +e
   local existing_stemcell
   existing_stemcell=$(bosh stemcells | grep "${os}" | awk '{print $2}' | tr -d "\*" | grep ^"${version}"$ )
   set -e
 
-  local stemcell_name
-
+  # Detect infrastructure by asking bosh itself
+  echo "[DEBUG] Detecting infrastructure via bosh env..."
   local infrastructure
-  if [ "${BOSH_LITE}" == "true"  ]; then
-    infrastructure="bosh-lite"
-    stemcell_name="bosh-warden-boshlite"
-  elif [ -d toolsmiths-env ]; then
-    infrastructure="gcp"
-    stemcell_name="bosh-google-kvm"
-  else
-    infrastructure="$(jq -r .iaas bbl-state/${BBL_STATE_DIR}/bbl-state.json)"
+  local stemcell_name
+  infrastructure=$(bosh env --json | jq -r '.Tables[].Rows[] | .cpi')
 
-    if [ "$infrastructure" = "aws" ]; then
-      stemcell_name="bosh-aws-xen-hvm"
-    elif [ "$infrastructure" = "gcp" ]; then
+  echo "[DEBUG] bosh env CPI: ${infrastructure}"
+
+  case "$infrastructure" in
+    *warden*|*boshlite*)
+      infrastructure="bosh-lite"
+      stemcell_name="bosh-warden-boshlite"
+      ;;
+    *google*)
+      infrastructure="gcp"
       stemcell_name="bosh-google-kvm"
-    elif [ "$infrastructure" = "vsphere" ]; then
+      ;;
+    *aws*)
+      infrastructure="aws"
+      stemcell_name="bosh-aws-xen-hvm"
+      ;;
+    *vsphere*)
+      infrastructure="vsphere"
       stemcell_name="bosh-vsphere-esxi"
-    elif [ "$infrastructure" = "azure" ]; then
+      ;;
+    *azure*)
+      infrastructure="azure"
       stemcell_name="bosh-azure-hyperv"
-    elif [ "$infrastructure" = "openstack" ]; then
+      ;;
+    *openstack*)
+      infrastructure="openstack"
       stemcell_name="bosh-openstack-kvm"
-    fi
-  fi
+      ;;
+    *)
+      echo "[ERROR] Could not detect infrastructure CPI from bosh env!"
+      exit 3
+      ;;
+  esac
+
+  echo "[DEBUG] Detected infra: ${infrastructure}"
+  echo "[DEBUG] Stemcell base name: ${stemcell_name}"
 
   stemcell_name="${stemcell_name}-${os}-go_agent"
   if [ "$version" = "latest" ]; then
@@ -514,27 +525,26 @@ upload_stemcell() {
     full_stemcell_url="${stemcells_url}/${stemcell_name}?v=${version}"
   fi
 
+  echo "[DEBUG] Full stemcell URL: ${full_stemcell_url}"
+
   # If bosh already has our stemcell, exit 0
   if [ "${existing_stemcell}" ]; then
-    echo "Task bosh-upload-stemcell-from-cf-deployment:"
-    echo "Stemcell '${stemcell_name}/${version}' already exists.  Skipping..."
+    echo "[INFO] Stemcell '${stemcell_name}/${version}' already exists. Skipping..."
     return
   fi
 
-  # If bosh.io doesn't have our stemcell, exit 2
+  # Check if bosh.io has this stemcell
   set +e
-  local stemcell_exists
   wget -S --spider "${full_stemcell_url}" > /dev/null 2>&1
-  stemcell_exists=$?
-  if [ ${stemcell_exists} -ne 0 ]; then
-    echo "Error: Could not find a '$os' stemcell for IaaS '$infrastructure' on bosh.io. Please double-check that the IaaS/OS combination is supported."
-    exit 2 #POSIX 'No such file or directory'
-  fi
+  local stemcell_exists=$?
   set -e
 
-  # ... otherwise, begin the upload process
-  bosh \
-    -n \
-    upload-stemcell \
-    "${full_stemcell_url}"
+  if [ ${stemcell_exists} -ne 0 ]; then
+    echo "[ERROR] Could not find a '$os' stemcell for IaaS '$infrastructure' on bosh.io."
+    exit 2
+  fi
+
+  # Otherwise, upload it
+  echo "[INFO] Uploading stemcell: ${stemcell_name}/${version}"
+  bosh -n upload-stemcell "${full_stemcell_url}"
 }
